### Numpy

Numpy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [2]:
# Visualizando a versão do Python e tbm a versão do pacote Numpy
import sys
import numpy as np

# Versão do Python
print(sys.version)
# Versão do Numpy
np.__version__

3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]


'1.17.4'

In [3]:
# Criando um array Numpy
array1 = np.arange(15)

In [4]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# Help
?array1

In [11]:
# Média
array1.mean()

7.0

In [8]:
array1.sum()

105

In [9]:
array1.min()

0

In [10]:
array1.max()

14

In [13]:
# Calcular o desvio padrão
array1.std()

4.320493798938574

### Utilizando List Comprehension em Arrays NumPy

In [15]:
# Utilizando List Comprehension em arrays Numpy
[x * x for x in array1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [16]:
# Utilizando List Comprehension em arrys Numpy
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

### Utilizando Função Lambda em Arrays Numpy

In [18]:
# Utilizando expressão lambda
list(filter(lambda x: x % 2 == 0, array1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [19]:
# Atenção com a notação
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [20]:
# Atenção com a notação
array1[array1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### Avaliando Performance

In [21]:
# Performance usando List Comprehension
# %timeit é um operador do Jupyter Notebook, 
# ele mede o tempo de execução de um comando
%timeit [x for x in array1 if x % 2 == 0]

6.95 µs ± 83.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
# Performance usando Numpy
# %timeit é um operador do Jupyter Notebook, 
# ele mede o tempo de execução de um comando
%timeit array1[array1 % 2 == 0]

2.11 µs ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Usando Operadores Lógicos

In [25]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [26]:
array1[array1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [27]:
# Operador lógico and
(array1 > 9) & (array1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [29]:
# Operador lógico or
(array1 > 13) | (array1 > 12)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True])

In [30]:
# Operador lógico or
array1[(array1 > 13) | (array1 < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [31]:
# Criando um arry Numpy com List Comprehension
array2 = np.array([x ** 3 for x in range(15)])

In [32]:
array2

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [34]:
# Criando um array Numpy com List Comprehension
array2 = np.array([True for x in range(15)])

In [35]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [36]:
# Usando um array como índice para outro array
array1[array2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])