### Numpy

Numpy oferece sequências de elementos que são mais eficientes que sequências padrões em Python

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]


'1.17.4'

In [2]:
# Cria um array preenchido com número 1
array1 = np.ones(4)

In [3]:
array2 = np.arange(15)

In [4]:
array_conc = np.concatenate((array1, array2))

In [5]:
array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

### Joining Arrays

In [6]:
a = np.ones((3,3))
# Cria uma matriz de zeros
b = np.zeros((3,3))

In [7]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Stack arrays in sequence vertically (row wise).
# Faz uma pilha de arrays em sequência verticalmente (row wise).
?np.vstack

In [14]:
# Stack arrays in sequence horizontally (column wise).
# Faz uma pilha de arrays em sequência horizontalmente (column wise)
?np.hstack

In [16]:
# Primeiro preenche as linhas
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# Primeiro preenche as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [18]:
# Joining arrays
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [19]:
# Stack 1-D arrays as columns into a 2-D array.
?np.column_stack

In [21]:
# Stack arrays in sequence vertically (row wise).
?np.row_stack

In [22]:
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [23]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Split Arrays

In [24]:
array3 = np.arange(16).reshape((4, 4)); array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
[array3_p1, array3_p2] = np.hsplit(array3, 2)

In [29]:
array3_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [30]:
array3_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [31]:
[array3_p1, array3_p2] = np.vsplit(array3, 2)

In [32]:
array3_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
array3_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Gravando e carregando dados com Numpy

In [34]:
dados = array3

In [35]:
np.save('dados_saved_v1', dados)

In [36]:
loaded_data = np.load('dados_saved_v1.npy')

In [37]:
loaded_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])