### Numpy

#### Arrays Numpy
Objetos multidimensionais com N dimensões.

#### Matrizes Numpy
Objetos com 2 dimensões.

A principal vantagem de utilizar matrizes com Numpy, é que este tipo de objeto possui convenientes notações para multiplicação de matrizes. Arrays e Matrizes Numpy possuem o atribute .T para retornar a transposta da matriz, enquanto objetos do tipo matriz possuem adicionalmente os atributos .I (Inversa) e .H(Transposta Conjugada).

Existem diferenças em operações de álgebra linear entre arrays e matrizes.

Muitas funções Numpy retornam arrays e não matrizes como objeto resultante.

In [2]:
import sys
import numpy as np

print(sys.version)

np.__version__

3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]


'1.17.4'

### Criando Matrizes

In [4]:
mat1 = np.matrix("1, 2, 3; 4, 5, 6")

print(mat1)

[[1 2 3]
 [4 5 6]]


In [5]:
type(mat1)

numpy.matrix

In [6]:
mat2 = np.matrix([ [1, 2, 3], [4, 5, 6] ])
print(mat2)

[[1 2 3]
 [4 5 6]]


In [8]:
type(mat2)

numpy.matrix

In [10]:
mat3 = np.matrix([ [0,10,0,0,0], [0,0,20,0,0], [0,0,0,30,0], [0,0,0,0,40], [0,0,0,0,0] ])
print(mat3)

[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]
 [ 0  0  0  0  0]]


In [11]:
type(mat3)

numpy.matrix

In [12]:
mat3[2, 3]

30

### Operações Matemáticas com Arrays e Matrizes

In [14]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
type(a)

numpy.ndarray

In [16]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [18]:
# convertendo a array em matriz
A = np.mat(a)
A

matrix([[1, 2],
        [3, 4]])

In [19]:
type(A)

numpy.matrix

In [20]:
A * A

matrix([[ 7, 10],
        [15, 22]])

In [22]:
# Usando o conceito matemático dot product (multiplicação de matrizes) com arrays
np.dot(a, a)

array([[ 7, 10],
       [15, 22]])

In [23]:
# Convertendo um array para Matriz
mat5 = np.asmatrix(a)

In [24]:
mat5

matrix([[1, 2],
        [3, 4]])

In [25]:
type(mat5)

numpy.matrix

In [26]:
mat5 * mat5

matrix([[ 7, 10],
        [15, 22]])

In [27]:
# Convertendo uma Matriz para Array
array2 = np.asarray(mat5)

In [29]:
type(array2)

numpy.ndarray

In [30]:
array2

array([[1, 2],
       [3, 4]])

In [31]:
array2 * array2

array([[ 1,  4],
       [ 9, 16]])